FROM python:3.12-slim
WORKDIR /app
COPY api/requirements/base.txt .
COPY api/requirements/prod.txt .
RUN pip install -r prod.txt
COPY api/ .
EXPOSE 8000
CMD ["gunicorn", "greenwich.wsgi:application", "--bind", "0.0.0.0:8000"]
